# Site settings
title:          Teaconomy
description:    "Spilling the Tea"
baseurl:        "/blogme/"
url:            "https://lynnear19.github.io"


# Author
author:
  name:         Lynn Lu
  url:          https://teaconomy.com
  email:        lynnlu.xia@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]
